// lib/terraform.ts
// Natural language -> reviewable Infrastructure-as-Code.
//
// Renders a syntactically valid Azure Terraform (HCL) plan from a parsed
// provisioning spec. The output is meant to be REVIEWED before any apply: it
// captures the resource group, PostgreSQL flexible server + database, a firewall
// rule, and tags (owner, environment, and destroy-on-date where present). The admin
// password is wired through a Terraform variable so the plaintext never appears in
// the generated file (see lib/secrets.ts for the runtime secret handling).

import type { TicketSpecInput } from "./types";

// Maps our compute tier + vCores to an Azure flexible-server sku_name.
// Mirrors the mapping the Azure adapter uses for the Burstable path and extends
// it for the General Purpose / Memory Optimized tiers.
function skuName(spec: Partial<TicketSpecInput>): string {
  const vCores = spec.vCores ?? 2;
  switch (spec.computeTier) {
    case "MemoryOptimized":
      return `MO_Standard_E${vCores}ds_v5`;
    case "GeneralPurpose":
      return `GP_Standard_D${vCores}ds_v5`;
    case "Burstable":
    default:
      return vCores === 1 ? "B_Standard_B1ms" : "B_Standard_B2s";
  }
}

// Converts an arbitrary identifier into a safe Terraform resource label.
function tfLabel(value: string | undefined, fallback: string): string {
  const cleaned = (value ?? "").toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "");
  return cleaned || fallback;
}

// Escapes a string for embedding inside a double-quoted HCL string.
function hcl(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// Renders an HCL tags map block body from key/value pairs, skipping empty values.
function renderTags(tags: Record<string, string | undefined>, indent: string): string {
  return Object.entries(tags)
    .filter(([, v]) => v && v.trim())
    .map(([k, v]) => `${indent}${k} = "${hcl(v as string)}"`)
    .join("\n");
}

export function generateTerraform(spec: Partial<TicketSpecInput>, owner?: string): string {
  const environment = spec.environment ?? "dev";
  const region = spec.requestedRegion ?? "eastus";
  const serverName = spec.serverName ?? "stackgate-server";
  const databaseName = spec.databaseName ?? "appdb";
  const adminUsername = spec.adminUsername ?? "appadmin";
  const storageMb = (spec.storageGb ?? 32) * 1024;
  const postgresVersion = process.env.AZURE_POSTGRES_VERSION ?? "16";
  const resourceGroupName = `rg-stackgate-${environment}`;
  const haMode = spec.highAvailability ? "ZoneRedundant" : null;
  const allowedIp = (spec.allowedIpRanges ?? "").split(",")[0]?.trim();

  const rgLabel = tfLabel(`${environment}`, "main");
  const serverLabel = tfLabel(serverName, "server");

  const tags = {
    environment,
    owner: owner ?? spec.teamName,
    team: spec.teamName,
    application: spec.applicationName,
    data_classification: spec.dataClassification,
    destroy_on: spec.destroyOnDate,
    managed_by: "StackGate",
  };

  const blocks: string[] = [];

  blocks.push(`# Generated by StackGate — reviewable Infrastructure-as-Code.
# This plan is for review only. Run "terraform plan" before any apply.
# The admin password is supplied via the "admin_password" variable and is never
# written into this file (StackGate stores a Key Vault reference, not the secret).

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "admin_password" {
  description = "Administrator password for the PostgreSQL flexible server."
  type        = string
  sensitive   = true
}`);

  blocks.push(`resource "azurerm_resource_group" "${rgLabel}" {
  name     = "${hcl(resourceGroupName)}"
  location = "${hcl(region)}"

  tags = {
${renderTags(tags, "    ")}
  }
}`);

  const haBlock = haMode
    ? `

  high_availability {
    mode = "${haMode}"
  }`
    : "";

  blocks.push(`resource "azurerm_postgresql_flexible_server" "${serverLabel}" {
  name                   = "${hcl(serverName)}"
  resource_group_name    = azurerm_resource_group.${rgLabel}.name
  location               = azurerm_resource_group.${rgLabel}.location
  version                = "${hcl(postgresVersion)}"
  administrator_login    = "${hcl(adminUsername)}"
  administrator_password = var.admin_password
  sku_name               = "${hcl(skuName(spec))}"
  storage_mb             = ${storageMb}
  backup_retention_days  = ${spec.backupRetentionDays ?? 7}${haBlock}

  tags = {
${renderTags(tags, "    ")}
  }
}`);

  blocks.push(`resource "azurerm_postgresql_flexible_server_database" "${tfLabel(databaseName, "db")}" {
  name      = "${hcl(databaseName)}"
  server_id = azurerm_postgresql_flexible_server.${serverLabel}.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}`);

  if (spec.networkMode === "public" && allowedIp) {
    // Derive a start/end address from the first allowed range. For a CIDR we keep it
    // simple and use the network address for both ends; a single IP maps to itself.
    const baseIp = allowedIp.split("/")[0];
    blocks.push(`resource "azurerm_postgresql_flexible_server_firewall_rule" "allowed_range" {
  name             = "stackgate-allowed-range"
  server_id        = azurerm_postgresql_flexible_server.${serverLabel}.id
  start_ip_address = "${hcl(baseIp)}"
  end_ip_address   = "${hcl(baseIp)}"
}`);
  }

  blocks.push(`output "fqdn" {
  value = azurerm_postgresql_flexible_server.${serverLabel}.fqdn
}

output "database_name" {
  value = azurerm_postgresql_flexible_server_database.${tfLabel(databaseName, "db")}.name
}`);

  return blocks.join("\n\n") + "\n";
}

// Conventional filename for the generated plan, used for downloads.
export function terraformFileName(spec: Partial<TicketSpecInput>): string {
  const base = tfLabel(spec.serverName, "stackgate");
  return `${base}.tf`;
}
